### PR TITLE
BUG-33362: Export native c++ rpc status code to java exception

### PR DESCRIPTION
**Pull request by ghost**
Haohui, here's new patch!

```
+      if (code == null) {
+        throw new IOException(message());
+      }
```

We need this guard so as to pass UT(s) for client.error(null, emptyRequest); and client.error2(null, emptyRequest);, in both case, code is null since server side implementation directly throws ServiceException, however, it's preferable to catch the exception and stack trace in client side.

### CODE REVIEW

**Comment by haohui** [comment]
bq. in both case, code is null since server side implementation directly throws ServiceException, however, it's preferable to catch the exception and stack trace in client side.

Where are the unit tests that you're pointing to?

**Comment by ghost** [comment]
TestRpcEngine.testProtoBufRandomException and TestRpcEngine.testProtoBufRpc. Internally, client.error and client.error2 are called for test.

**Comment by ghost** [comment]
commented back
and please address all comments
looks like that you missed the last comment..

> see my comment above. That's why I choose to 'throw new IOException(message());' when code is null, and then there's no need to do Preconditions.CheckState(c != null); However, still need to handle cases like 
> case UNIMPLEMENTED:
> case EINVAL:
> case EXCEPTION:
> to throw exception bound to them, respectively.

**Comment by haohui** [comment]
bq. however, it's preferable to catch the exception and stack trace in client side.

I'm not sure where the "preferable" is coming from. I don't see why it needs to be a special case.

bq.  However, still need to handle cases like 
case UNIMPLEMENTED:
case EINVAL:
case EXCEPTION:

Please note they are RuntimeException which can be directly thrown.

**Comment by ghost** [comment]
bq. I'm not sure where the "preferable" is coming from. I don't see why it needs to be a special case.

> "preferable" means we've to catch exception directly thrown by server side, in other words. 
> 'Preconditions.CheckState(c != null);' throws exception that breaks the tests for client.error and client.error2 since ServiceException is expected, however, without the guard,
> 
> ```
> +    Errno code = code();
> +    if (code == null) {
> +      throw new IOException(message());
> +    }
> ```
> 
> 'Preconditions.CheckState(code != null);' will throw IllegalStateException because code is null in the case of client.error and client.error2.

**Comment by ghost** [comment]
b.q. Please note they are RuntimeException which can be directly thrown.
That's true. If we don't handle these special cases explicitly in checkForIOException.
The line in the following '(IOException) constructor.newInstance(message);' will throw exception because not all exceptions bound to Errno are IOException, e.g. 

```
+    UNIMPLEMENTED(3, NotImplementedException.class),
```

```
+    private IOException newException(String message) {
+      if (constructor != null) {
+        try {
+          return (IOException) constructor.newInstance(message);
```

Special handling in 

```
+    switch (code) {
+    case UNIMPLEMENTED:
+      throw new NotImplementedException(message());
+    case EINVAL:
+      throw new IllegalArgumentException(message());
+    case EXCEPTION:
+      throw new IOException(message());
```

is a good place to take care non-IOException with cast or translation or thrown as RuntimeException.

**Comment by haohui** [comment]
bq. however, without the guard, 'Preconditions.CheckState(code != null);' will throw IllegalStateException because code is null in the case of client.error and client.error2.

You are probably aware of you're making a bold statement -- I'm sorry but this does not make any sense at all --- `code` should never equals to null unless you have a bug in Java / C++ mapping.

The precondition specifies a contract and it caught an issue, meaning that the code have a serious bug here.

A 30-second breakpoint shows that this line is wrong here:

```
return Errno.ERRNO_MAP.get(ByteBuffer.wrap(state, 0, 8).getInt());
```

If you look at how `Status` is constructed you're obviously getting garbage here.

bq. is a good place to take care non-IOException with cast or translation or thrown as RuntimeException.

Why not rename `checkForIOException` to `checkForException`?

**Comment by ghost** [comment]
bq. If you look at how Status is constructed you're obviously getting garbage here.

> my bad, [size][code][msg1][': '][msg2] are structured in position of [0.3][4...7][len1][': '][len2], respectively. Need to get code from [4...7]. Will verify if code is not null in any case so as to introduce precondition. Thanks for pointing that out.

bq. Why not rename checkForIOException to checkForException?

> I agree with this change.

**Pull request closed without merging**
