### PR TITLE
Fix for issue #39.  RPC calls are thread safe.

### PR DESCRIPTION
**Pull request by jamesclampffer**
Fix for #39.

I tested it on my perf_tests branch and didn't have any issues with multithreading.  Please let me know if it looks like I missed anything.

### CODE REVIEW

**Comment by jamesclampffer** [comment]
It looks like I'm hitting some deadlock issues.  I need to determine if it's due to my change or if it's something going on with the code I'm linking this into.  Closing this request until I sort things out.

**Comment by haohui** [comment]
It turns out this patch breaks the unit test `TestRpcEngine`. It looks like the event loop has a dangling pointer to RPCEngine / RPCConnection. @jamesclampffer , can you please take a look at it? Thanks.

**Comment by haohui** [comment]
Given a second thought, I'm unsure this is a good idea. The application should be able to spawn multiple RPCEngine on different io_service to spread the processing across multi-core. Maybe what should be done here is to provide an interface to post the request into the event loop.

**Comment by jamesclampffer** [comment]
I'll take a look at this today.

Wouldn't it be simpler to allow the user to specify how many threads call io_service.Run() in the RPC engine?  That seems like the least invasive change and the locking, once fixed, is intended to allow for callbacks to be handled in the context of any thread that has called io_service.Run().

**Comment by haohui** [comment]
There can be only one thread running for an instance of io serivce. The
same io serivce will be reused for both roc engine and the reader, so it
makes more sense to make it explicit in the API level and let the
application decide running the RPc engine / reader with different io
services.

**Comment by jamesclampffer** [comment]
Is the one thread per instance of io_service a restriction due to the libhdfs++ architecture, or am I misunderstanding something in the asio documentation? 

http://www.boost.org/doc/libs/1_40_0/doc/html/boost_asio/overview/core/threads.html
"Multiple threads may call io_service::run() to set up a pool of threads from which completion handlers may be invoked"

I agree that setting up an io_service for the rpc_engine and another the readers would be a good idea from a separation of concerns point of view.  For my application it would be nice to have an API that lets the user pass an initialized IoService object that wraps the asio::io_service primarily to provide options for the client to add their own logging and debug hooks.

**Pull request closed without merging**
